# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='someModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somestring', models.CharField(max_length=100)),
                ('somenumber', models.IntegerField()),
                ('currenttime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
