# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tophat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalURL', models.CharField(max_length=500)),
                ('newURL', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='someModel',
        ),
    ]
