# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tophat_app', '0002_auto_20160119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='newURL',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
